version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - jekyll build
artifacts:
  files:
    - '**/*'
  base-directory: "src/_site"